services:
  openocd:
    image: openocd-esp32:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
        OPENOCD_INTERFACE: esp_usb_jtag # Set the interface type
        OPENOCD_TARGET: esp32s3 # Set the target type
        HOST_IP: 0.0.0.0 # Set the IP address to bind OpenOCD to
    ports:
     - "6666:6666" 
     - "4444:4444" # Telnet server port
     - "3333:3333" # GDB remote debugging port
    devices:
     - /dev/bus/usb # Mount the USB device


